const cartTypes = {
  FILL_CART: "FILL_CART",
  UPDATE_CART: "UPDATE_CART",
  REMOVE_CART: "REMOVE_CART",
  INCREASE_CART: "INCREASE_CART",
  DECREASE_CART: "DECREASE_CART",
  REMOVE_ENTIRE_CART: "REMOVE_ENTIRE_CART",
};
export default cartTypes;
