const counterCompareTypes = {
    INCREASE_COMPARE_COUNTER: "INCREASE_COMPARE_COUNTER",
    DECREASE_COMPARE_COUNTER: "DECREASE_COMPARE_COUNTER",
    RESET_COMPARE_COUNTER: "RESET_COMPARE_COUNTER",
  };
  
  export default counterCompareTypes;