const favoritesTypes = {
         ADD_TO_FAVORITES: "ADD_TO_FAVORITES",
         REMOVE_FROM_FAVORITES: "REMOVE_FROM_FAVORITES",
         INCREMENT_FAVORITES_COUNT: "INCREMENT_FAVORITES_COUNT",
         DECREMENT_FAVORITES_COUNT: "DECREMENT_FAVORITES_COUNT"
};

export default favoritesTypes;

